// All GPC data for Phonics Reef
// Each GPC has: id, grapheme, phoneme (IPA), sound description, words with gap position

export const LEVELS = [
  {
    id: 1,
    name: "Shallow Shore",
    emoji: "🏝️",
    description: "Short vowels",
    color: "#FCD34D",
    gpcs: ["short_a", "short_e", "short_i", "short_o", "short_u"],
  },
  {
    id: 2,
    name: "Rock Pool",
    emoji: "🐚",
    description: "Doubled consonants",
    color: "#FFB347",
    gpcs: ["ff", "ll", "ss", "zz", "ck", "nk", "bb", "dd", "pp", "rr", "tt"],
  },
  {
    id: 3,
    name: "Seagrass Bed",
    emoji: "🌾",
    description: "Consonant digraphs",
    color: "#86EFAC",
    gpcs: ["sh", "ch", "th", "ng"],
  },
  {
    id: 4,
    name: "Reef Flats",
    emoji: "🐡",
    description: "Consonant blends",
    color: "#67E8F9",
    gpcs: ["bl", "br", "cl", "cr", "dr", "fl", "fr", "gl", "gr", "pl", "pr", "sk", "sl", "sm", "sn", "sp", "st", "sw", "tr", "tw"],
  },
  {
    id: 5,
    name: "Coral Cove",
    emoji: "🪸",
    description: "Common vowel digraphs",
    color: "#FF6B6B",
    gpcs: ["ai", "ee", "oa", "igh", "oo_long", "oo_short", "ar", "or", "ur"],
  },
  {
    id: 6,
    name: "Kelp Forest",
    emoji: "🌿",
    description: "Long vowels + magic E",
    color: "#4ECDC4",
    gpcs: ["a_e", "i_e", "o_e", "u_e", "ea_long", "ea_short", "er_stressed", "er_unstressed", "ow_loud", "ow_soft", "ie_long", "ie_short"],
  },
  {
    id: 7,
    name: "Deep Blue",
    emoji: "🌊",
    description: "Diphthongs + tricky vowels",
    color: "#45B7D1",
    gpcs: ["oi", "ou", "oy", "aw", "au", "air", "ear_near", "ear_bear", "are", "ue", "ew", "oe"],
  },
  {
    id: 8,
    name: "Shipwreck Bay",
    emoji: "⚓",
    description: "Silent/tricky consonants",
    color: "#96CEB4",
    gpcs: ["tch", "dge", "kn", "wr", "ph", "wh", "gn", "mb"],
  },
  {
    id: 9,
    name: "Treasure Trove",
    emoji: "💎",
    description: "Word building",
    color: "#FFEAA7",
    gpcs: ["suffix_s", "suffix_ing", "suffix_ed", "prefix_un", "compound", "ending_le"],
  },
];

export const GPCS = {
  // LEVEL 1 — Short vowels
  short_a: {
    grapheme: "a",
    sound: "/æ/",
    hint: "short A — as in cat",
    words: [
      { word: "cat", gap: [1, 1], display: "c_t", answer: "a", distractors: ["e", "i", "o"] },
      { word: "bag", gap: [1, 1], display: "b_g", answer: "a", distractors: ["e", "i", "o"] },
      { word: "hat", gap: [1, 1], display: "h_t", answer: "a", distractors: ["e", "i", "o"] },
      { word: "man", gap: [1, 1], display: "m_n", answer: "a", distractors: ["e", "i", "o"] },
      { word: "tap", gap: [1, 1], display: "t_p", answer: "a", distractors: ["e", "i", "o"] },
    ],
  },
  short_e: {
    grapheme: "e",
    sound: "/ɛ/",
    hint: "short E — as in bed",
    words: [
      { word: "bed", gap: [1, 1], display: "b_d", answer: "e", distractors: ["a", "i", "u"] },
      { word: "hen", gap: [1, 1], display: "h_n", answer: "e", distractors: ["a", "i", "u"] },
      { word: "leg", gap: [1, 1], display: "l_g", answer: "e", distractors: ["a", "i", "u"] },
      { word: "pet", gap: [1, 1], display: "p_t", answer: "e", distractors: ["a", "i", "u"] },
      { word: "web", gap: [1, 1], display: "w_b", answer: "e", distractors: ["a", "i", "u"] },
    ],
  },
  short_i: {
    grapheme: "i",
    sound: "/ɪ/",
    hint: "short I — as in big",
    words: [
      { word: "big", gap: [1, 1], display: "b_g", answer: "i", distractors: ["a", "e", "u"] },
      { word: "dip", gap: [1, 1], display: "d_p", answer: "i", distractors: ["a", "e", "u"] },
      { word: "fin", gap: [1, 1], display: "f_n", answer: "i", distractors: ["a", "e", "u"] },
      { word: "hit", gap: [1, 1], display: "h_t", answer: "i", distractors: ["a", "e", "u"] },
      { word: "pig", gap: [1, 1], display: "p_g", answer: "i", distractors: ["a", "e", "u"] },
    ],
  },
  short_o: {
    grapheme: "o",
    sound: "/ɒ/",
    hint: "short O — as in dog",
    words: [
      { word: "dog", gap: [1, 1], display: "d_g", answer: "o", distractors: ["a", "i", "u"] },
      { word: "fog", gap: [1, 1], display: "f_g", answer: "o", distractors: ["a", "i", "u"] },
      { word: "hop", gap: [1, 1], display: "h_p", answer: "o", distractors: ["a", "i", "u"] },
      { word: "log", gap: [1, 1], display: "l_g", answer: "o", distractors: ["a", "i", "u"] },
      { word: "pot", gap: [1, 1], display: "p_t", answer: "o", distractors: ["a", "i", "u"] },
    ],
  },
  short_u: {
    grapheme: "u",
    sound: "/ʌ/",
    hint: "short U — as in bus",
    words: [
      { word: "bus", gap: [1, 1], display: "b_s", answer: "u", distractors: ["a", "i", "o"] },
      { word: "cut", gap: [1, 1], display: "c_t", answer: "u", distractors: ["a", "i", "o"] },
      { word: "fun", gap: [1, 1], display: "f_n", answer: "u", distractors: ["a", "i", "o"] },
      { word: "mug", gap: [1, 1], display: "m_g", answer: "u", distractors: ["a", "i", "o"] },
      { word: "run", gap: [1, 1], display: "r_n", answer: "u", distractors: ["a", "i", "o"] },
    ],
  },

  // LEVEL 2 — Foundation: doubled consonants (simplest Year 1 patterns)
  ff: {
    grapheme: "ff",
    sound: "/f/",
    hint: "double F — same sound as F",
    words: [
      { word: "off",   gap: [0, 1], display: "__f",    answer: "ff", distractors: ["f", "ph"] },
      { word: "cliff", gap: [2, 3], display: "cl__",   answer: "ff", distractors: ["f", "ph"] },
      { word: "huff",  gap: [1, 2], display: "h__",    answer: "ff", distractors: ["f", "ph"] },
      { word: "stiff", gap: [2, 3], display: "st__",   answer: "ff", distractors: ["f", "ph"] },
      { word: "sniff", gap: [2, 3], display: "sn__",   answer: "ff", distractors: ["f", "v"]  },
    ],
  },
  ll: {
    grapheme: "ll",
    sound: "/l/",
    hint: "double L — same sound as L",
    words: [
      { word: "bell",  gap: [1, 2], display: "b__",    answer: "ll", distractors: ["l", "le"] },
      { word: "fill",  gap: [1, 2], display: "f__",    answer: "ll", distractors: ["l", "le"] },
      { word: "tall",  gap: [1, 2], display: "t__",    answer: "ll", distractors: ["l", "al"] },
      { word: "spell", gap: [2, 3], display: "sp__",   answer: "ll", distractors: ["l", "le"] },
      { word: "hill",  gap: [1, 2], display: "h__",    answer: "ll", distractors: ["l", "le"] },
    ],
  },
  ss: {
    grapheme: "ss",
    sound: "/s/",
    hint: "double S — same sound as S",
    words: [
      { word: "miss",  gap: [1, 2], display: "m__",    answer: "ss", distractors: ["s", "ce"] },
      { word: "fuss",  gap: [1, 2], display: "f__",    answer: "ss", distractors: ["s", "ce"] },
      { word: "class", gap: [2, 3], display: "cl__",   answer: "ss", distractors: ["s", "se"] },
      { word: "press", gap: [2, 3], display: "pr__",   answer: "ss", distractors: ["s", "se"] },
      { word: "kiss",  gap: [1, 2], display: "k__",    answer: "ss", distractors: ["s", "ce"] },
    ],
  },
  zz: {
    grapheme: "zz",
    sound: "/z/",
    hint: "double Z — buzzy sound!",
    words: [
      { word: "buzz",  gap: [1, 2], display: "b__",    answer: "zz", distractors: ["z", "s"]  },
      { word: "fizz",  gap: [1, 2], display: "f__",    answer: "zz", distractors: ["z", "s"]  },
      { word: "jazz",  gap: [1, 2], display: "j__",    answer: "zz", distractors: ["z", "s"]  },
      { word: "fuzz",  gap: [1, 2], display: "f__",    answer: "zz", distractors: ["z", "s"]  },
      { word: "fizzy", gap: [1, 2], display: "f__y",   answer: "zz", distractors: ["z", "s"]  },
    ],
  },
  ck: {
    grapheme: "ck",
    sound: "/k/",
    hint: "C and K together — same sound as K",
    words: [
      { word: "back",  gap: [1, 2], display: "b__",    answer: "ck", distractors: ["k", "c"]  },
      { word: "neck",  gap: [1, 2], display: "n__",    answer: "ck", distractors: ["k", "c"]  },
      { word: "kick",  gap: [1, 2], display: "k__",    answer: "ck", distractors: ["k", "c"]  },
      { word: "sock",  gap: [1, 2], display: "s__",    answer: "ck", distractors: ["k", "c"]  },
      { word: "duck",  gap: [1, 2], display: "d__",    answer: "ck", distractors: ["k", "c"]  },
    ],
  },
  nk: {
    grapheme: "nk",
    sound: "/ŋk/",
    hint: "N and K together — think, bank",
    words: [
      { word: "bank",  gap: [1, 2], display: "b__",    answer: "nk", distractors: ["ng", "nc"] },
      { word: "sink",  gap: [1, 2], display: "s__",    answer: "nk", distractors: ["ng", "nc"] },
      { word: "drink", gap: [2, 3], display: "dr__",   answer: "nk", distractors: ["ng", "nc"] },
      { word: "blank", gap: [2, 3], display: "bl__",   answer: "nk", distractors: ["ng", "nc"] },
      { word: "trunk", gap: [2, 3], display: "tr__",   answer: "nk", distractors: ["ng", "nc"] },
    ],
  },

  bb: {
    grapheme: "bb",
    sound: "/b/",
    hint: "double B",
    words: [
      { word: "rabbit",  gap: [2, 3], display: "ra__it",  answer: "bb", distractors: ["b", "pp", "dd"] },
      { word: "bubble",  gap: [2, 3], display: "bu__le",  answer: "bb", distractors: ["b", "pp", "dd"] },
      { word: "hobby",   gap: [2, 3], display: "ho__y",   answer: "bb", distractors: ["b", "pp", "dd"] },
      { word: "dribble", gap: [3, 4], display: "dri__le", answer: "bb", distractors: ["b", "pp", "dd"] },
      { word: "cobble",  gap: [2, 3], display: "co__le",  answer: "bb", distractors: ["b", "pp", "dd"] },
    ],
  },
  dd: {
    grapheme: "dd",
    sound: "/d/",
    hint: "double D",
    words: [
      { word: "odd",    gap: [1, 2], display: "o__",    answer: "dd", distractors: ["d", "tt", "bb"] },
      { word: "muddy",  gap: [2, 3], display: "mu__y",  answer: "dd", distractors: ["d", "tt", "bb"] },
      { word: "paddle", gap: [2, 3], display: "pa__le", answer: "dd", distractors: ["d", "tt", "bb"] },
      { word: "middle", gap: [2, 3], display: "mi__le", answer: "dd", distractors: ["d", "tt", "bb"] },
      { word: "puddle", gap: [2, 3], display: "pu__le", answer: "dd", distractors: ["d", "tt", "bb"] },
    ],
  },
  nn: {
    grapheme: "nn",
    sound: "/n/",
    hint: "double N",
    words: [
      { word: "funny",   gap: [2, 3], display: "fu__y",   answer: "nn", distractors: ["n", "mm", "rr"] },
      { word: "running", gap: [2, 3], display: "ru__ing", answer: "nn", distractors: ["n", "mm", "rr"] },
      { word: "tennis",  gap: [2, 3], display: "te__is",  answer: "nn", distractors: ["n", "mm", "rr"] },
      { word: "nanny",   gap: [2, 3], display: "na__y",   answer: "nn", distractors: ["n", "mm", "rr"] },
      { word: "sunny",   gap: [2, 3], display: "su__y",   answer: "nn", distractors: ["n", "mm", "rr"] },
    ],
  },
  pp: {
    grapheme: "pp",
    sound: "/p/",
    hint: "double P",
    words: [
      { word: "happy",  gap: [2, 3], display: "ha__y",  answer: "pp", distractors: ["p", "bb", "tt"] },
      { word: "pepper", gap: [2, 3], display: "pe__er", answer: "pp", distractors: ["p", "bb", "tt"] },
      { word: "copper", gap: [2, 3], display: "co__er", answer: "pp", distractors: ["p", "bb", "tt"] },
      { word: "puppy",  gap: [2, 3], display: "pu__y",  answer: "pp", distractors: ["p", "bb", "tt"] },
      { word: "supper", gap: [2, 3], display: "su__er", answer: "pp", distractors: ["p", "bb", "tt"] },
    ],
  },
  rr: {
    grapheme: "rr",
    sound: "/r/",
    hint: "double R",
    words: [
      { word: "arrow",  gap: [1, 2], display: "a__ow",  answer: "rr", distractors: ["r", "nn", "ll"] },
      { word: "carrot", gap: [2, 3], display: "ca__ot", answer: "rr", distractors: ["r", "nn", "ll"] },
      { word: "sorry",  gap: [2, 3], display: "so__y",  answer: "rr", distractors: ["r", "nn", "ll"] },
      { word: "hurry",  gap: [2, 3], display: "hu__y",  answer: "rr", distractors: ["r", "nn", "ll"] },
      { word: "parrot", gap: [2, 3], display: "pa__ot", answer: "rr", distractors: ["r", "nn", "ll"] },
    ],
  },
  tt: {
    grapheme: "tt",
    sound: "/t/",
    hint: "double T",
    words: [
      { word: "attic",  gap: [1, 2], display: "a__ic",  answer: "tt", distractors: ["t", "dd", "pp"] },
      { word: "butter", gap: [2, 3], display: "bu__er", answer: "tt", distractors: ["t", "dd", "pp"] },
      { word: "kitten", gap: [2, 3], display: "ki__en", answer: "tt", distractors: ["t", "dd", "pp"] },
      { word: "mitten", gap: [2, 3], display: "mi__en", answer: "tt", distractors: ["t", "dd", "pp"] },
      { word: "cotton", gap: [2, 3], display: "co__on", answer: "tt", distractors: ["t", "dd", "pp"] },
    ],
  },

  // LEVEL 3 — Consonant digraphs
  sh: {
    grapheme: "sh",
    sound: "/ʃ/",
    hint: "SH — like putting your finger to your lips",
    words: [
      { word: "ship",  gap: [0, 1], display: "__ip",  answer: "sh", distractors: ["ch", "th", "wh"] },
      { word: "fish",  gap: [2, 3], display: "fi__",  answer: "sh", distractors: ["ch", "th", "wh"] },
      { word: "shell", gap: [0, 1], display: "__ell", answer: "sh", distractors: ["ch", "th", "wh"] },
      { word: "shop",  gap: [0, 1], display: "__op",  answer: "sh", distractors: ["ch", "th", "wh"] },
      { word: "rush",  gap: [2, 3], display: "ru__",  answer: "sh", distractors: ["ch", "th", "wh"] },
    ],
  },
  ch: {
    grapheme: "ch",
    sound: "/tʃ/",
    hint: "CH — like a train!",
    words: [
      { word: "chip", gap: [0, 1], display: "__ip", answer: "ch", distractors: ["sh", "th", "wh"] },
      { word: "chin", gap: [0, 1], display: "__in", answer: "ch", distractors: ["sh", "th", "wh"] },
      { word: "much", gap: [2, 3], display: "mu__", answer: "ch", distractors: ["sh", "th", "wh"] },
      { word: "such", gap: [2, 3], display: "su__", answer: "ch", distractors: ["sh", "th", "wh"] },
      { word: "rich", gap: [2, 3], display: "ri__", answer: "ch", distractors: ["sh", "th", "wh"] },
    ],
  },
  th: {
    grapheme: "th",
    sound: "/θ/",
    hint: "TH — tongue between your teeth",
    words: [
      { word: "this",  gap: [0, 1], display: "__is",  answer: "th", distractors: ["sh", "ch", "wh"] },
      { word: "that",  gap: [0, 1], display: "__at",  answer: "th", distractors: ["sh", "ch", "wh"] },
      { word: "thin",  gap: [0, 1], display: "__in",  answer: "th", distractors: ["sh", "ch", "wh"] },
      { word: "thick", gap: [0, 1], display: "__ick", answer: "th", distractors: ["sh", "ch", "wh"] },
      { word: "with",  gap: [2, 3], display: "wi__",  answer: "th", distractors: ["sh", "ch", "wh"] },
    ],
  },
  ng: {
    grapheme: "ng",
    sound: "/ŋ/",
    hint: "NG — the humming sound at the end",
    words: [
      { word: "ring", gap: [2, 3], display: "ri__", answer: "ng", distractors: ["nk", "nt", "nd"] },
      { word: "song", gap: [2, 3], display: "so__", answer: "ng", distractors: ["nk", "nt", "nd"] },
      { word: "long", gap: [2, 3], display: "lo__", answer: "ng", distractors: ["nk", "nt", "nd"] },
      { word: "bang", gap: [2, 3], display: "ba__", answer: "ng", distractors: ["nk", "nt", "nd"] },
      { word: "king", gap: [2, 3], display: "ki__", answer: "ng", distractors: ["nk", "nt", "nd"] },
    ],
  },

  // LEVEL 4 — Consonant blends
  bl: {
    grapheme: "bl",
    sound: "/bl/",
    hint: "B and L blend",
    words: [
      { word: "black", gap: [0, 1], display: "__ack",  answer: "bl", distractors: ["cl", "fl", "sl"] },
      { word: "blue",  gap: [0, 1], display: "__ue",   answer: "bl", distractors: ["cl", "fl", "sl"] },
      { word: "blow",  gap: [0, 1], display: "__ow",   answer: "bl", distractors: ["cl", "fl", "sl"] },
      { word: "blank", gap: [0, 1], display: "__ank",  answer: "bl", distractors: ["cl", "fl", "sl"] },
      { word: "bless", gap: [0, 1], display: "__ess",  answer: "bl", distractors: ["cl", "fl", "sl"] },
    ],
  },
  br: {
    grapheme: "br",
    sound: "/br/",
    hint: "B and R blend",
    words: [
      { word: "bread",  gap: [0, 1], display: "__ead",  answer: "br", distractors: ["cr", "dr", "tr"] },
      { word: "brick",  gap: [0, 1], display: "__ick",  answer: "br", distractors: ["cr", "dr", "tr"] },
      { word: "brown",  gap: [0, 1], display: "__own",  answer: "br", distractors: ["cr", "dr", "tr"] },
      { word: "bring",  gap: [0, 1], display: "__ing",  answer: "br", distractors: ["cr", "dr", "tr"] },
      { word: "brush",  gap: [0, 1], display: "__ush",  answer: "br", distractors: ["cr", "dr", "tr"] },
    ],
  },
  cl: {
    grapheme: "cl",
    sound: "/kl/",
    hint: "C and L blend",
    words: [
      { word: "clap",   gap: [0, 1], display: "__ap",   answer: "cl", distractors: ["bl", "fl", "sl"] },
      { word: "clam",   gap: [0, 1], display: "__am",   answer: "cl", distractors: ["bl", "fl", "sl"] },
      { word: "clock",  gap: [0, 1], display: "__ock",  answer: "cl", distractors: ["bl", "fl", "sl"] },
      { word: "club",   gap: [0, 1], display: "__ub",   answer: "cl", distractors: ["bl", "fl", "sl"] },
      { word: "clown",  gap: [0, 1], display: "__own",  answer: "cl", distractors: ["bl", "fl", "sl"] },
    ],
  },
  cr: {
    grapheme: "cr",
    sound: "/kr/",
    hint: "C and R blend",
    words: [
      { word: "crab",  gap: [0, 1], display: "__ab",  answer: "cr", distractors: ["br", "dr", "tr"] },
      { word: "cram",  gap: [0, 1], display: "__am",  answer: "cr", distractors: ["br", "dr", "tr"] },
      { word: "crop",  gap: [0, 1], display: "__op",  answer: "cr", distractors: ["br", "dr", "tr"] },
      { word: "crow",  gap: [0, 1], display: "__ow",  answer: "cr", distractors: ["br", "dr", "tr"] },
      { word: "crush", gap: [0, 1], display: "__ush", answer: "cr", distractors: ["br", "dr", "tr"] },
    ],
  },
  dr: {
    grapheme: "dr",
    sound: "/dr/",
    hint: "D and R blend",
    words: [
      { word: "drum",  gap: [0, 1], display: "__um",  answer: "dr", distractors: ["br", "cr", "tr"] },
      { word: "drip",  gap: [0, 1], display: "__ip",  answer: "dr", distractors: ["br", "cr", "tr"] },
      { word: "drop",  gap: [0, 1], display: "__op",  answer: "dr", distractors: ["br", "cr", "tr"] },
      { word: "drag",  gap: [0, 1], display: "__ag",  answer: "dr", distractors: ["br", "cr", "tr"] },
      { word: "dress", gap: [0, 1], display: "__ess", answer: "dr", distractors: ["br", "cr", "tr"] },
    ],
  },
  fl: {
    grapheme: "fl",
    sound: "/fl/",
    hint: "F and L blend",
    words: [
      { word: "flag",   gap: [0, 1], display: "__ag",   answer: "fl", distractors: ["bl", "cl", "sl"] },
      { word: "flat",   gap: [0, 1], display: "__at",   answer: "fl", distractors: ["bl", "cl", "sl"] },
      { word: "flip",   gap: [0, 1], display: "__ip",   answer: "fl", distractors: ["bl", "cl", "sl"] },
      { word: "flock",  gap: [0, 1], display: "__ock",  answer: "fl", distractors: ["bl", "cl", "sl"] },
      { word: "fled",   gap: [0, 1], display: "__ed",   answer: "fl", distractors: ["bl", "cl", "sl"] },
    ],
  },
  fr: {
    grapheme: "fr",
    sound: "/fr/",
    hint: "F and R blend",
    words: [
      { word: "frog",   gap: [0, 1], display: "__og",   answer: "fr", distractors: ["br", "cr", "dr"] },
      { word: "from",   gap: [0, 1], display: "__om",   answer: "fr", distractors: ["br", "cr", "dr"] },
      { word: "free",   gap: [0, 1], display: "__ee",   answer: "fr", distractors: ["br", "cr", "dr"] },
      { word: "frill",  gap: [0, 1], display: "__ill",  answer: "fr", distractors: ["br", "cr", "dr"] },
      { word: "frost",  gap: [0, 1], display: "__ost",  answer: "fr", distractors: ["br", "cr", "dr"] },
    ],
  },
  gl: {
    grapheme: "gl",
    sound: "/gl/",
    hint: "G and L blend",
    words: [
      { word: "glad",  gap: [0, 1], display: "__ad",  answer: "gl", distractors: ["bl", "cl", "fl"] },
      { word: "glass", gap: [0, 1], display: "__ass", answer: "gl", distractors: ["bl", "cl", "fl"] },
      { word: "glow",  gap: [0, 1], display: "__ow",  answer: "gl", distractors: ["bl", "cl", "fl"] },
      { word: "glue",  gap: [0, 1], display: "__ue",  answer: "gl", distractors: ["bl", "cl", "fl"] },
      { word: "glen",  gap: [0, 1], display: "__en",  answer: "gl", distractors: ["bl", "cl", "fl"] },
    ],
  },
  gr: {
    grapheme: "gr",
    sound: "/gr/",
    hint: "G and R blend",
    words: [
      { word: "grab",  gap: [0, 1], display: "__ab",  answer: "gr", distractors: ["br", "cr", "dr"] },
      { word: "green", gap: [0, 1], display: "__een", answer: "gr", distractors: ["br", "cr", "dr"] },
      { word: "grew",  gap: [0, 1], display: "__ew",  answer: "gr", distractors: ["br", "cr", "dr"] },
      { word: "grin",  gap: [0, 1], display: "__in",  answer: "gr", distractors: ["br", "cr", "dr"] },
      { word: "grip",  gap: [0, 1], display: "__ip",  answer: "gr", distractors: ["br", "cr", "dr"] },
    ],
  },
  pl: {
    grapheme: "pl",
    sound: "/pl/",
    hint: "P and L blend",
    words: [
      { word: "plan", gap: [0, 1], display: "__an", answer: "pl", distractors: ["bl", "cl", "fl"] },
      { word: "play", gap: [0, 1], display: "__ay", answer: "pl", distractors: ["bl", "cl", "fl"] },
      { word: "plop", gap: [0, 1], display: "__op", answer: "pl", distractors: ["bl", "cl", "fl"] },
      { word: "plug", gap: [0, 1], display: "__ug", answer: "pl", distractors: ["bl", "cl", "fl"] },
      { word: "plum", gap: [0, 1], display: "__um", answer: "pl", distractors: ["bl", "cl", "fl"] },
    ],
  },
  pr: {
    grapheme: "pr",
    sound: "/pr/",
    hint: "P and R blend",
    words: [
      { word: "print", gap: [0, 1], display: "__int", answer: "pr", distractors: ["br", "cr", "dr"] },
      { word: "prod",  gap: [0, 1], display: "__od",  answer: "pr", distractors: ["br", "cr", "dr"] },
      { word: "prop",  gap: [0, 1], display: "__op",  answer: "pr", distractors: ["br", "cr", "dr"] },
      { word: "pray",  gap: [0, 1], display: "__ay",  answer: "pr", distractors: ["br", "cr", "dr"] },
      { word: "pram",  gap: [0, 1], display: "__am",  answer: "pr", distractors: ["br", "cr", "dr"] },
    ],
  },
  sk: {
    grapheme: "sk",
    sound: "/sk/",
    hint: "S and K blend",
    words: [
      { word: "skip",  gap: [0, 1], display: "__ip",  answer: "sk", distractors: ["sl", "sm", "sn"] },
      { word: "skin",  gap: [0, 1], display: "__in",  answer: "sk", distractors: ["sl", "sm", "sn"] },
      { word: "sky",   gap: [0, 1], display: "__y",   answer: "sk", distractors: ["sl", "sm", "sn"] },
      { word: "skull", gap: [0, 1], display: "__ull", answer: "sk", distractors: ["sl", "sm", "sn"] },
      { word: "skid",  gap: [0, 1], display: "__id",  answer: "sk", distractors: ["sl", "sm", "sn"] },
    ],
  },
  sl: {
    grapheme: "sl",
    sound: "/sl/",
    hint: "S and L blend",
    words: [
      { word: "slip", gap: [0, 1], display: "__ip", answer: "sl", distractors: ["bl", "cl", "fl"] },
      { word: "slow", gap: [0, 1], display: "__ow", answer: "sl", distractors: ["bl", "cl", "fl"] },
      { word: "slam", gap: [0, 1], display: "__am", answer: "sl", distractors: ["bl", "cl", "fl"] },
      { word: "slap", gap: [0, 1], display: "__ap", answer: "sl", distractors: ["bl", "cl", "fl"] },
      { word: "slim", gap: [0, 1], display: "__im", answer: "sl", distractors: ["bl", "cl", "fl"] },
    ],
  },
  sm: {
    grapheme: "sm",
    sound: "/sm/",
    hint: "S and M blend",
    words: [
      { word: "smell", gap: [0, 1], display: "__ell",  answer: "sm", distractors: ["sn", "sp", "st"] },
      { word: "smile", gap: [0, 1], display: "__ile",  answer: "sm", distractors: ["sn", "sp", "st"] },
      { word: "small", gap: [0, 1], display: "__all",  answer: "sm", distractors: ["sn", "sp", "st"] },
      { word: "smash", gap: [0, 1], display: "__ash",  answer: "sm", distractors: ["sn", "sp", "st"] },
      { word: "smug",  gap: [0, 1], display: "__ug",   answer: "sm", distractors: ["sn", "sp", "st"] },
    ],
  },
  sn: {
    grapheme: "sn",
    sound: "/sn/",
    hint: "S and N blend",
    words: [
      { word: "snap", gap: [0, 1], display: "__ap", answer: "sn", distractors: ["sm", "sp", "st"] },
      { word: "snow", gap: [0, 1], display: "__ow", answer: "sn", distractors: ["sm", "sp", "st"] },
      { word: "snag", gap: [0, 1], display: "__ag", answer: "sn", distractors: ["sm", "sp", "st"] },
      { word: "snip", gap: [0, 1], display: "__ip", answer: "sn", distractors: ["sm", "sp", "st"] },
      { word: "snob", gap: [0, 1], display: "__ob", answer: "sn", distractors: ["sm", "sp", "st"] },
    ],
  },
  sp: {
    grapheme: "sp",
    sound: "/sp/",
    hint: "S and P blend",
    words: [
      { word: "spot", gap: [0, 1], display: "__ot", answer: "sp", distractors: ["sk", "sl", "st"] },
      { word: "spin", gap: [0, 1], display: "__in", answer: "sp", distractors: ["sk", "sl", "st"] },
      { word: "span", gap: [0, 1], display: "__an", answer: "sp", distractors: ["sk", "sl", "st"] },
      { word: "spud", gap: [0, 1], display: "__ud", answer: "sp", distractors: ["sk", "sl", "st"] },
      { word: "spit", gap: [0, 1], display: "__it", answer: "sp", distractors: ["sk", "sl", "st"] },
    ],
  },
  st: {
    grapheme: "st",
    sound: "/st/",
    hint: "S and T blend",
    words: [
      { word: "step", gap: [0, 1], display: "__ep", answer: "st", distractors: ["sk", "sl", "sp"] },
      { word: "stop", gap: [0, 1], display: "__op", answer: "st", distractors: ["sk", "sl", "sp"] },
      { word: "stem", gap: [0, 1], display: "__em", answer: "st", distractors: ["sk", "sl", "sp"] },
      { word: "stub", gap: [0, 1], display: "__ub", answer: "st", distractors: ["sk", "sl", "sp"] },
      { word: "stab", gap: [0, 1], display: "__ab", answer: "st", distractors: ["sk", "sl", "sp"] },
    ],
  },
  sw: {
    grapheme: "sw",
    sound: "/sw/",
    hint: "S and W blend",
    words: [
      { word: "swim", gap: [0, 1], display: "__im", answer: "sw", distractors: ["sl", "sm", "sn"] },
      { word: "swam", gap: [0, 1], display: "__am", answer: "sw", distractors: ["sl", "sm", "sn"] },
      { word: "swot", gap: [0, 1], display: "__ot", answer: "sw", distractors: ["sl", "sm", "sn"] },
      { word: "swab", gap: [0, 1], display: "__ab", answer: "sw", distractors: ["sl", "sm", "sn"] },
      { word: "swum", gap: [0, 1], display: "__um", answer: "sw", distractors: ["sl", "sm", "sn"] },
    ],
  },
  tr: {
    grapheme: "tr",
    sound: "/tr/",
    hint: "T and R blend",
    words: [
      { word: "trip", gap: [0, 1], display: "__ip", answer: "tr", distractors: ["br", "cr", "dr"] },
      { word: "tree", gap: [0, 1], display: "__ee", answer: "tr", distractors: ["br", "cr", "dr"] },
      { word: "trap", gap: [0, 1], display: "__ap", answer: "tr", distractors: ["br", "cr", "dr"] },
      { word: "trim", gap: [0, 1], display: "__im", answer: "tr", distractors: ["br", "cr", "dr"] },
      { word: "trot", gap: [0, 1], display: "__ot", answer: "tr", distractors: ["br", "cr", "dr"] },
    ],
  },
  tw: {
    grapheme: "tw",
    sound: "/tw/",
    hint: "T and W blend",
    words: [
      { word: "twin",  gap: [0, 1], display: "__in",   answer: "tw", distractors: ["sw", "tr", "dr"] },
      { word: "twig",  gap: [0, 1], display: "__ig",   answer: "tw", distractors: ["sw", "tr", "dr"] },
      { word: "twit",  gap: [0, 1], display: "__it",   answer: "tw", distractors: ["sw", "tr", "dr"] },
      { word: "twill", gap: [0, 1], display: "__ill",  answer: "tw", distractors: ["sw", "tr", "dr"] },
      { word: "twang", gap: [0, 1], display: "__ang",  answer: "tw", distractors: ["sw", "tr", "dr"] },
    ],
  },

  // LEVEL 5 — Common vowel digraphs
  ai: {
    grapheme: "ai",
    sound: "/eɪ/",
    hint: "sounds like the letter A",
    words: [
      { word: "rain", gap: [1, 2], display: "r__n", answer: "ai", distractors: ["ay", "ea"] },
      { word: "wait", gap: [1, 2], display: "w__t", answer: "ai", distractors: ["ay", "ee"] },
      { word: "train", gap: [2, 3], display: "tr__n", answer: "ai", distractors: ["ay", "oa"] },
      { word: "paid", gap: [1, 2], display: "p__d", answer: "ai", distractors: ["ay", "ea"] },
      { word: "afraid", gap: [3, 4], display: "afr__d", answer: "ai", distractors: ["ay", "ee"] },
    ],
  },
  ee: {
    grapheme: "ee",
    sound: "/iː/",
    hint: "long E sound — like a big smile!",
    words: [
      { word: "tree", gap: [1, 2], display: "tr__", answer: "ee", distractors: ["ea", "ie"] },
      { word: "green", gap: [2, 3], display: "gr__n", answer: "ee", distractors: ["ea", "ie"] },
      { word: "meet", gap: [1, 2], display: "m__t", answer: "ee", distractors: ["ea", "ie"] },
      { word: "week", gap: [1, 2], display: "w__k", answer: "ee", distractors: ["ea", "ie"] },
      { word: "sleep", gap: [2, 3], display: "sl__p", answer: "ee", distractors: ["ea", "ie"] },
    ],
  },
  oa: {
    grapheme: "oa",
    sound: "/əʊ/",
    hint: "long O sound",
    words: [
      { word: "boat", gap: [1, 2], display: "b__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "coat", gap: [1, 2], display: "c__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "road", gap: [1, 2], display: "r__d", answer: "oa", distractors: ["oe", "ow"] },
      { word: "goat", gap: [1, 2], display: "g__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "toast", gap: [1, 2], display: "t__st", answer: "oa", distractors: ["oe", "ow"] },
    ],
  },
  igh: {
    grapheme: "igh",
    sound: "/aɪ/",
    hint: "long I sound — the gh is silent!",
    words: [
      { word: "night", gap: [1, 3], display: "n___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "light", gap: [1, 3], display: "l___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "right", gap: [1, 3], display: "r___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "bright", gap: [2, 4], display: "br___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "fight", gap: [1, 3], display: "f___t", answer: "igh", distractors: ["ie", "i-e"] },
    ],
  },
  oo_long: {
    grapheme: "oo",
    sound: "/uː/",
    hint: "long OO sound — like a ghost saying BOO!",
    words: [
      { word: "food", gap: [1, 2], display: "f__d", answer: "oo", distractors: ["ue", "ew"] },
      { word: "moon", gap: [1, 2], display: "m__n", answer: "oo", distractors: ["ue", "ew"] },
      { word: "pool", gap: [1, 2], display: "p__l", answer: "oo", distractors: ["ue", "ew"] },
      { word: "cool", gap: [1, 2], display: "c__l", answer: "oo", distractors: ["ue", "ew"] },
      { word: "spoon", gap: [2, 3], display: "sp__n", answer: "oo", distractors: ["ue", "ew"] },
    ],
  },
  oo_short: {
    grapheme: "oo",
    sound: "/ʊ/",
    hint: "short OO sound — like putting on a hood",
    words: [
      { word: "book", gap: [1, 2], display: "b__k", answer: "oo", distractors: ["ou", "u"] },
      { word: "cook", gap: [1, 2], display: "c__k", answer: "oo", distractors: ["ou", "u"] },
      { word: "foot", gap: [1, 2], display: "f__t", answer: "oo", distractors: ["ou", "u"] },
      { word: "wood", gap: [1, 2], display: "w__d", answer: "oo", distractors: ["ou", "u"] },
      { word: "good", gap: [1, 2], display: "g__d", answer: "oo", distractors: ["ou", "u"] },
    ],
  },
  ar: {
    grapheme: "ar",
    sound: "/ɑː/",
    hint: "say AAAH like at the doctor",
    words: [
      { word: "car", gap: [1, 2], display: "c__", answer: "ar", distractors: ["or", "er"] },
      { word: "star", gap: [2, 3], display: "st__", answer: "ar", distractors: ["or", "er"] },
      { word: "park", gap: [1, 2], display: "p__k", answer: "ar", distractors: ["or", "er"] },
      { word: "farm", gap: [1, 2], display: "f__m", answer: "ar", distractors: ["or", "er"] },
      { word: "shark", gap: [2, 3], display: "sh__k", answer: "ar", distractors: ["or", "er"] },
    ],
  },
  or: {
    grapheme: "or",
    sound: "/ɔː/",
    hint: "like saying OR",
    words: [
      { word: "for", gap: [1, 2], display: "f__", answer: "or", distractors: ["ar", "aw"] },
      { word: "short", gap: [2, 3], display: "sh__t", answer: "or", distractors: ["ar", "aw"] },
      { word: "corn", gap: [1, 2], display: "c__n", answer: "or", distractors: ["ar", "aw"] },
      { word: "storm", gap: [2, 3], display: "st__m", answer: "or", distractors: ["ar", "aw"] },
      { word: "sport", gap: [2, 3], display: "sp__t", answer: "or", distractors: ["ar", "aw"] },
    ],
  },
  ur: {
    grapheme: "ur",
    sound: "/ɜː/",
    hint: "like saying ER with your mouth relaxed",
    words: [
      { word: "turn", gap: [1, 2], display: "t__n", answer: "ur", distractors: ["er", "ir"] },
      { word: "hurt", gap: [1, 2], display: "h__t", answer: "ur", distractors: ["er", "ir"] },
      { word: "burst", gap: [1, 2], display: "b__st", answer: "ur", distractors: ["er", "ir"] },
      { word: "purple", gap: [1, 2], display: "p__ple", answer: "ur", distractors: ["er", "ir"] },
      { word: "nurse", gap: [1, 2], display: "n__se", answer: "ur", distractors: ["er", "ir"] },
    ],
  },

  // LEVEL 6 — Magic E patterns
  a_e: {
    grapheme: "a-e",
    sound: "/eɪ/",
    hint: "magic E makes A say its name!",
    words: [
      { word: "made", gap: [1, 1], display: "m__de", answer: "a", distractors: ["e", "i", "o"] },
      { word: "came", gap: [1, 1], display: "c__me", answer: "a", distractors: ["e", "i", "o"] },
      { word: "same", gap: [1, 1], display: "s__me", answer: "a", distractors: ["e", "i", "o"] },
      { word: "take", gap: [1, 1], display: "t__ke", answer: "a", distractors: ["e", "i", "o"] },
      { word: "safe", gap: [1, 1], display: "s__fe", answer: "a", distractors: ["e", "i", "o"] },
    ],
  },
  i_e: {
    grapheme: "i-e",
    sound: "/aɪ/",
    hint: "magic E makes I say its name!",
    words: [
      { word: "five", gap: [1, 1], display: "f__ve", answer: "i", distractors: ["a", "e", "o"] },
      { word: "ride", gap: [1, 1], display: "r__de", answer: "i", distractors: ["a", "e", "o"] },
      { word: "like", gap: [1, 1], display: "l__ke", answer: "i", distractors: ["a", "e", "o"] },
      { word: "time", gap: [1, 1], display: "t__me", answer: "i", distractors: ["a", "e", "o"] },
      { word: "side", gap: [1, 1], display: "s__de", answer: "i", distractors: ["a", "e", "o"] },
    ],
  },
  o_e: {
    grapheme: "o-e",
    sound: "/əʊ/",
    hint: "magic E makes O say its name!",
    words: [
      { word: "home", gap: [1, 1], display: "h__me", answer: "o", distractors: ["a", "i", "u"] },
      { word: "hope", gap: [1, 1], display: "h__pe", answer: "o", distractors: ["a", "i", "u"] },
      { word: "hole", gap: [1, 1], display: "h__le", answer: "o", distractors: ["a", "i", "u"] },
      { word: "bone", gap: [1, 1], display: "b__ne", answer: "o", distractors: ["a", "i", "u"] },
      { word: "woke", gap: [1, 1], display: "w__ke", answer: "o", distractors: ["a", "i", "u"] },
    ],
  },
  u_e: {
    grapheme: "u-e",
    sound: "/uː/",
    hint: "magic E makes U say its name!",
    words: [
      { word: "tube", gap: [1, 1], display: "t__be", answer: "u", distractors: ["a", "i", "o"] },
      { word: "tune", gap: [1, 1], display: "t__ne", answer: "u", distractors: ["a", "i", "o"] },
      { word: "rule", gap: [1, 1], display: "r__le", answer: "u", distractors: ["a", "i", "o"] },
      { word: "rude", gap: [1, 1], display: "r__de", answer: "u", distractors: ["a", "i", "o"] },
      { word: "cube", gap: [1, 1], display: "c__be", answer: "u", distractors: ["a", "i", "o"] },
    ],
  },

  // LEVEL 6 — Alternative vowel sounds
  ea_long: {
    grapheme: "ea",
    sound: "/iː/",
    hint: "long E sound — like EE",
    words: [
      { word: "sea", gap: [1, 2], display: "s__", answer: "ea", distractors: ["ee", "ie"] },
      { word: "dream", gap: [2, 3], display: "dr__m", answer: "ea", distractors: ["ee", "ie"] },
      { word: "meat", gap: [1, 2], display: "m__t", answer: "ea", distractors: ["ee", "ie"] },
      { word: "beach", gap: [1, 2], display: "b__ch", answer: "ea", distractors: ["ee", "ie"] },
      { word: "read", gap: [1, 2], display: "r__d", answer: "ea", distractors: ["ee", "ie"] },
    ],
  },
  ea_short: {
    grapheme: "ea",
    sound: "/ɛ/",
    hint: "short E sound — like in bed",
    words: [
      { word: "head", gap: [1, 2], display: "h__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "bread", gap: [2, 3], display: "br__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "spread", gap: [3, 4], display: "spr__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "thread", gap: [3, 4], display: "thr__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "dread", gap: [2, 3], display: "dr__d", answer: "ea", distractors: ["e", "ee"] },
    ],
  },
  er_stressed: {
    grapheme: "er",
    sound: "/ɜː/",
    hint: "stressed ER — like in HER",
    words: [
      { word: "her", gap: [1, 2], display: "h__", answer: "er", distractors: ["ur", "ir"] },
      { word: "term", gap: [1, 2], display: "t__m", answer: "er", distractors: ["ur", "ir"] },
      { word: "verb", gap: [1, 2], display: "v__b", answer: "er", distractors: ["ur", "ir"] },
      { word: "stern", gap: [2, 3], display: "st__n", answer: "er", distractors: ["ur", "ir"] },
      { word: "person", gap: [1, 2], display: "p__son", answer: "er", distractors: ["ur", "ir"] },
    ],
  },
  er_unstressed: {
    grapheme: "er",
    sound: "/ə/",
    hint: "soft ER at the end — like in BUTTER",
    words: [
      { word: "better", gap: [3, 4], display: "bett__", answer: "er", distractors: ["or", "ar"] },
      { word: "under", gap: [3, 4], display: "und__", answer: "er", distractors: ["or", "ar"] },
      { word: "summer", gap: [4, 5], display: "summ__", answer: "er", distractors: ["or", "ar"] },
      { word: "winter", gap: [4, 5], display: "wint__", answer: "er", distractors: ["or", "ar"] },
      { word: "river", gap: [3, 4], display: "riv__", answer: "er", distractors: ["or", "ar"] },
    ],
  },
  ow_loud: {
    grapheme: "ow",
    sound: "/aʊ/",
    hint: "OW! like it hurts!",
    words: [
      { word: "now", gap: [1, 2], display: "n__", answer: "ow", distractors: ["ou", "oa"] },
      { word: "brown", gap: [2, 3], display: "br__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "town", gap: [1, 2], display: "t__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "crown", gap: [2, 3], display: "cr__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "growl", gap: [2, 3], display: "gr__l", answer: "ow", distractors: ["ou", "oa"] },
    ],
  },
  ow_soft: {
    grapheme: "ow",
    sound: "/əʊ/",
    hint: "soft OW — like SNOW",
    words: [
      { word: "snow", gap: [2, 3], display: "sn__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "blow", gap: [2, 3], display: "bl__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "grow", gap: [2, 3], display: "gr__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "show", gap: [2, 3], display: "sh__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "flow", gap: [2, 3], display: "fl__", answer: "ow", distractors: ["oa", "oe"] },
    ],
  },
  ie_long: {
    grapheme: "ie",
    sound: "/aɪ/",
    hint: "long I sound",
    words: [
      { word: "pie", gap: [1, 2], display: "p__", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "tie", gap: [1, 2], display: "t__", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "cried", gap: [2, 3], display: "cr__d", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "tried", gap: [2, 3], display: "tr__d", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "dried", gap: [2, 3], display: "dr__d", answer: "ie", distractors: ["igh", "i-e"] },
    ],
  },
  ie_short: {
    grapheme: "ie",
    sound: "/iː/",
    hint: "long E sound — like EE",
    words: [
      { word: "chief", gap: [2, 3], display: "ch__f", answer: "ie", distractors: ["ee", "ea"] },
      { word: "field", gap: [2, 3], display: "f__ld", answer: "ie", distractors: ["ee", "ea"] },
      { word: "thief", gap: [2, 3], display: "th__f", answer: "ie", distractors: ["ee", "ea"] },
      { word: "piece", gap: [1, 2], display: "p__ce", answer: "ie", distractors: ["ee", "ea"] },
      { word: "shield", gap: [2, 3], display: "sh__ld", answer: "ie", distractors: ["ee", "ea"] },
    ],
  },

  oi: {
    grapheme: "oi",
    sound: "/ɔɪ/",
    hint: "OI — like saying 'oy!' in surprise",
    words: [
      { word: "join",  gap: [1, 2], display: "j__n",  answer: "oi", distractors: ["oy", "ou", "oa"] },
      { word: "coin",  gap: [1, 2], display: "c__n",  answer: "oi", distractors: ["oy", "ou", "oa"] },
      { word: "point", gap: [1, 2], display: "p__nt", answer: "oi", distractors: ["oy", "ou", "oa"] },
      { word: "soil",  gap: [1, 2], display: "s__l",  answer: "oi", distractors: ["oy", "ou", "oa"] },
      { word: "foil",  gap: [1, 2], display: "f__l",  answer: "oi", distractors: ["oy", "ou", "oa"] },
    ],
  },
  ou: {
    grapheme: "ou",
    sound: "/aʊ/",
    hint: "OU — like saying 'ouch!'",
    words: [
      { word: "out",   gap: [0, 1], display: "__t",    answer: "ou", distractors: ["ow", "oa", "oo"] },
      { word: "mouth", gap: [1, 2], display: "m__th",  answer: "ou", distractors: ["ow", "oa", "oo"] },
      { word: "sound", gap: [1, 2], display: "s__nd",  answer: "ou", distractors: ["ow", "oa", "oo"] },
      { word: "cloud", gap: [2, 3], display: "cl__d",  answer: "ou", distractors: ["ow", "oa", "oo"] },
      { word: "found", gap: [1, 2], display: "f__nd",  answer: "ou", distractors: ["ow", "oa", "oo"] },
    ],
  },
  oy: {
    grapheme: "oy",
    sound: "/ɔɪ/",
    hint: "OY — at the end of words",
    words: [
      { word: "boy",   gap: [1, 2], display: "b__",    answer: "oy", distractors: ["oi", "ay", "ow"] },
      { word: "toy",   gap: [1, 2], display: "t__",    answer: "oy", distractors: ["oi", "ay", "ow"] },
      { word: "joy",   gap: [1, 2], display: "j__",    answer: "oy", distractors: ["oi", "ay", "ow"] },
      { word: "enjoy", gap: [3, 4], display: "enj__",  answer: "oy", distractors: ["oi", "ay", "ow"] },
      { word: "annoy", gap: [3, 4], display: "ann__",  answer: "oy", distractors: ["oi", "ay", "ow"] },
    ],
  },

  aw: {
    grapheme: "aw",
    sound: "/ɔː/",
    hint: "like OR — mouth open wide!",
    words: [
      { word: "saw", gap: [1, 2], display: "s__", answer: "aw", distractors: ["au", "or"] },
      { word: "draw", gap: [2, 3], display: "dr__", answer: "aw", distractors: ["au", "or"] },
      { word: "yawn", gap: [1, 2], display: "y__n", answer: "aw", distractors: ["au", "or"] },
      { word: "crawl", gap: [2, 3], display: "cr__l", answer: "aw", distractors: ["au", "or"] },
      { word: "claw", gap: [2, 3], display: "cl__", answer: "aw", distractors: ["au", "or"] },
    ],
  },
  au: {
    grapheme: "au",
    sound: "/ɔː/",
    hint: "like OR — same sound, different spelling!",
    words: [
      { word: "author", gap: [1, 2], display: "__thor", answer: "au", distractors: ["aw", "or"] },
      { word: "August", gap: [1, 2], display: "__gust", answer: "au", distractors: ["aw", "or"] },
      { word: "dinosaur", gap: [5, 6], display: "dinos__r", answer: "au", distractors: ["aw", "or"] },
      { word: "astronaut", gap: [6, 7], display: "astron__t", answer: "au", distractors: ["aw", "or"] },
      { word: "sauce", gap: [1, 2], display: "s__ce", answer: "au", distractors: ["aw", "or"] },
    ],
  },
  air: {
    grapheme: "air",
    sound: "/ɛː/",
    hint: "like saying AIR",
    words: [
      { word: "fair", gap: [1, 3], display: "f___", answer: "air", distractors: ["are", "ear"] },
      { word: "pair", gap: [1, 3], display: "p___", answer: "air", distractors: ["are", "ear"] },
      { word: "hair", gap: [1, 3], display: "h___", answer: "air", distractors: ["are", "ear"] },
      { word: "chair", gap: [2, 4], display: "ch___", answer: "air", distractors: ["are", "ear"] },
      { word: "stair", gap: [2, 4], display: "st___", answer: "air", distractors: ["are", "ear"] },
    ],
  },
  ear_near: {
    grapheme: "ear",
    sound: "/ɪə/",
    hint: "like HEAR — rhymes with NEAR",
    words: [
      { word: "dear", gap: [1, 3], display: "d___", answer: "ear", distractors: ["eer", "air"] },
      { word: "hear", gap: [1, 3], display: "h___", answer: "ear", distractors: ["eer", "air"] },
      { word: "near", gap: [1, 3], display: "n___", answer: "ear", distractors: ["eer", "air"] },
      { word: "year", gap: [1, 3], display: "y___", answer: "ear", distractors: ["eer", "air"] },
      { word: "clear", gap: [2, 4], display: "cl___", answer: "ear", distractors: ["eer", "air"] },
    ],
  },
  ear_bear: {
    grapheme: "ear",
    sound: "/ɛː/",
    hint: "like BEAR — rhymes with CARE",
    words: [
      { word: "bear", gap: [1, 3], display: "b___", answer: "ear", distractors: ["air", "are"] },
      { word: "pear", gap: [1, 3], display: "p___", answer: "ear", distractors: ["air", "are"] },
      { word: "wear", gap: [1, 3], display: "w___", answer: "ear", distractors: ["air", "are"] },
      { word: "swear", gap: [2, 4], display: "sw___", answer: "ear", distractors: ["air", "are"] },
      { word: "tear", gap: [1, 3], display: "t___", answer: "ear", distractors: ["air", "are"] },
    ],
  },
  are: {
    grapheme: "are",
    sound: "/ɛː/",
    hint: "like CARE — same sound as air and bear!",
    words: [
      { word: "bare", gap: [1, 3], display: "b___", answer: "are", distractors: ["air", "ear"] },
      { word: "dare", gap: [1, 3], display: "d___", answer: "are", distractors: ["air", "ear"] },
      { word: "care", gap: [1, 3], display: "c___", answer: "are", distractors: ["air", "ear"] },
      { word: "share", gap: [2, 4], display: "sh___", answer: "are", distractors: ["air", "ear"] },
      { word: "spare", gap: [2, 4], display: "sp___", answer: "are", distractors: ["air", "ear"] },
    ],
  },
  ue: {
    grapheme: "ue",
    sound: "/uː/",
    hint: "long OO sound — like TRUE",
    words: [
      { word: "blue", gap: [2, 3], display: "bl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "clue", gap: [2, 3], display: "cl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "true", gap: [2, 3], display: "tr__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "glue", gap: [2, 3], display: "gl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "due", gap: [1, 2], display: "d__", answer: "ue", distractors: ["ew", "oo"] },
    ],
  },
  ew: {
    grapheme: "ew",
    sound: "/uː/",
    hint: "long OO sound — like NEW",
    words: [
      { word: "new", gap: [1, 2], display: "n__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "few", gap: [1, 2], display: "f__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "grew", gap: [2, 3], display: "gr__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "flew", gap: [2, 3], display: "fl__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "threw", gap: [3, 4], display: "thr__", answer: "ew", distractors: ["ue", "oo"] },
    ],
  },
  oe: {
    grapheme: "oe",
    sound: "/əʊ/",
    hint: "long O sound — like TOE",
    words: [
      { word: "toe", gap: [1, 2], display: "t__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "goes", gap: [1, 2], display: "g__s", answer: "oe", distractors: ["ow", "oa"] },
      { word: "foe", gap: [1, 2], display: "f__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "doe", gap: [1, 2], display: "d__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "hoe", gap: [1, 2], display: "h__", answer: "oe", distractors: ["ow", "oa"] },
    ],
  },

  // LEVEL 4 — Consonant patterns
  tch: {
    grapheme: "tch",
    sound: "/tʃ/",
    hint: "like CH — the T is silent!",
    words: [
      { word: "catch", gap: [2, 4], display: "ca___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "fetch", gap: [2, 4], display: "fe___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "witch", gap: [2, 4], display: "wi___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "notch", gap: [2, 4], display: "no___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "hutch", gap: [2, 4], display: "hu___", answer: "tch", distractors: ["ch", "sh"] },
    ],
  },
  dge: {
    grapheme: "dge",
    sound: "/dʒ/",
    hint: "like J — badge rhymes with age!",
    words: [
      { word: "badge", gap: [2, 4], display: "ba___", answer: "dge", distractors: ["ge", "j"] },
      { word: "edge", gap: [1, 3], display: "e___", answer: "dge", distractors: ["ge", "j"] },
      { word: "bridge", gap: [3, 5], display: "bri___", answer: "dge", distractors: ["ge", "j"] },
      { word: "fudge", gap: [2, 4], display: "fu___", answer: "dge", distractors: ["ge", "j"] },
      { word: "nudge", gap: [2, 4], display: "nu___", answer: "dge", distractors: ["ge", "j"] },
    ],
  },
  kn: {
    grapheme: "kn",
    sound: "/n/",
    hint: "the K is silent — just say N!",
    words: [
      { word: "knock", gap: [0, 1], display: "__ock", answer: "kn", distractors: ["n", "gn"] },
      { word: "know", gap: [0, 1], display: "__ow", answer: "kn", distractors: ["n", "gn"] },
      { word: "knee", gap: [0, 1], display: "__ee", answer: "kn", distractors: ["n", "gn"] },
      { word: "knit", gap: [0, 1], display: "__it", answer: "kn", distractors: ["n", "gn"] },
      { word: "knife", gap: [0, 1], display: "__ife", answer: "kn", distractors: ["n", "gn"] },
    ],
  },
  wr: {
    grapheme: "wr",
    sound: "/r/",
    hint: "the W is silent — just say R!",
    words: [
      { word: "write", gap: [0, 1], display: "__ite", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrong", gap: [0, 1], display: "__ong", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrap", gap: [0, 1], display: "__ap", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrist", gap: [0, 1], display: "__ist", answer: "wr", distractors: ["r", "wh"] },
      { word: "wreck", gap: [0, 1], display: "__eck", answer: "wr", distractors: ["r", "wh"] },
    ],
  },
  ph: {
    grapheme: "ph",
    sound: "/f/",
    hint: "sounds like F — phone has no F!",
    words: [
      { word: "phone", gap: [0, 1], display: "__one", answer: "ph", distractors: ["f", "wh"] },
      { word: "photo", gap: [0, 1], display: "__oto", answer: "ph", distractors: ["f", "wh"] },
      { word: "dolphin", gap: [3, 4], display: "dol__in", answer: "ph", distractors: ["f", "wh"] },
      { word: "elephant", gap: [4, 5], display: "ele__ant", answer: "ph", distractors: ["f", "wh"] },
      { word: "alphabet", gap: [4, 5], display: "alp__abet", answer: "ph", distractors: ["f", "wh"] },
    ],
  },
  wh: {
    grapheme: "wh",
    sound: "/w/",
    hint: "sounds like W — when, where, which!",
    words: [
      { word: "when", gap: [0, 1], display: "__en", answer: "wh", distractors: ["w", "ph"] },
      { word: "where", gap: [0, 1], display: "__ere", answer: "wh", distractors: ["w", "ph"] },
      { word: "which", gap: [0, 1], display: "__ich", answer: "wh", distractors: ["w", "ph"] },
      { word: "wheel", gap: [0, 1], display: "__eel", answer: "wh", distractors: ["w", "ph"] },
      { word: "while", gap: [0, 1], display: "__ile", answer: "wh", distractors: ["w", "ph"] },
    ],
  },

  gn: {
    grapheme: "gn",
    sound: "/n/",
    hint: "the G is silent — just say N!",
    words: [
      { word: "gnaw",   gap: [0, 1], display: "__aw",   answer: "gn", distractors: ["n", "kn", "wr"] },
      { word: "gnat",   gap: [0, 1], display: "__at",   answer: "gn", distractors: ["n", "kn", "wr"] },
      { word: "gnome",  gap: [0, 1], display: "__ome",  answer: "gn", distractors: ["n", "kn", "wr"] },
      { word: "gnash",  gap: [0, 1], display: "__ash",  answer: "gn", distractors: ["n", "kn", "wr"] },
      { word: "gnarled", gap: [0, 1], display: "__arled", answer: "gn", distractors: ["n", "kn", "wr"] },
    ],
  },
  mb: {
    grapheme: "mb",
    sound: "/m/",
    hint: "silent B — the B is quiet!",
    words: [
      { word: "lamb",  gap: [2, 3], display: "la__",  answer: "mb", distractors: ["m", "mm", "nd"] },
      { word: "climb", gap: [3, 4], display: "cli__", answer: "mb", distractors: ["m", "mm", "nd"] },
      { word: "thumb", gap: [3, 4], display: "thu__", answer: "mb", distractors: ["m", "mm", "nd"] },
      { word: "comb",  gap: [2, 3], display: "co__",  answer: "mb", distractors: ["m", "mm", "nd"] },
      { word: "limb",  gap: [2, 3], display: "li__",  answer: "mb", distractors: ["m", "mm", "nd"] },
    ],
  },

  // LEVEL 9 — Word building
  suffix_s: {
    grapheme: "-s / -es",
    sound: "plural",
    hint: "add S or ES to make more than one",
    words: [
      { word: "cats", gap: [3, 3], display: "cat_", answer: "s", distractors: ["es", "ing"] },
      { word: "dogs", gap: [3, 3], display: "dog_", answer: "s", distractors: ["es", "ing"] },
      { word: "catches", gap: [5, 6], display: "catch__", answer: "es", distractors: ["s", "ing"] },
      { word: "dishes", gap: [4, 5], display: "dish__", answer: "es", distractors: ["s", "ing"] },
      { word: "boxes", gap: [3, 4], display: "box__", answer: "es", distractors: ["s", "ing"] },
    ],
  },
  suffix_ing: {
    grapheme: "-ing",
    sound: "present",
    hint: "add ING to show something is happening now",
    words: [
      { word: "jumping", gap: [4, 6], display: "jump___", answer: "ing", distractors: ["ed", "er"] },
      { word: "running", gap: [4, 6], display: "runn___", answer: "ing", distractors: ["ed", "er"] },
      { word: "hunting", gap: [4, 6], display: "hunt___", answer: "ing", distractors: ["ed", "er"] },
      { word: "fishing", gap: [4, 6], display: "fish___", answer: "ing", distractors: ["ed", "er"] },
      { word: "playing", gap: [4, 6], display: "play___", answer: "ing", distractors: ["ed", "er"] },
    ],
  },
  suffix_ed: {
    grapheme: "-ed",
    sound: "past",
    hint: "add ED to show something already happened",
    words: [
      { word: "jumped", gap: [4, 5], display: "jump__", answer: "ed", distractors: ["ing", "er"] },
      { word: "hunted", gap: [4, 5], display: "hunt__", answer: "ed", distractors: ["ing", "er"] },
      { word: "painted", gap: [5, 6], display: "paint__", answer: "ed", distractors: ["ing", "er"] },
      { word: "shouted", gap: [5, 6], display: "shout__", answer: "ed", distractors: ["ing", "er"] },
      { word: "landed", gap: [4, 5], display: "land__", answer: "ed", distractors: ["ing", "er"] },
    ],
  },
  prefix_un: {
    grapheme: "un-",
    sound: "opposite",
    hint: "UN at the start means NOT or opposite",
    words: [
      { word: "unhappy", gap: [0, 1], display: "__happy", answer: "un", distractors: ["re", "dis"] },
      { word: "undo", gap: [0, 1], display: "__do", answer: "un", distractors: ["re", "dis"] },
      { word: "unlock", gap: [0, 1], display: "__lock", answer: "un", distractors: ["re", "dis"] },
      { word: "unfair", gap: [0, 1], display: "__fair", answer: "un", distractors: ["re", "dis"] },
      { word: "unload", gap: [0, 1], display: "__load", answer: "un", distractors: ["re", "dis"] },
    ],
  },
  compound: {
    grapheme: "compound",
    sound: "two words",
    hint: "two words joined together make a new word!",
    words: [
      { word: "football", gap: [4, 7], display: "foot____", answer: "ball", distractors: ["park", "play"] },
      { word: "bedroom", gap: [3, 6], display: "bed____", answer: "room", distractors: ["side", "time"] },
      { word: "sunshine", gap: [3, 7], display: "sun_____", answer: "shine", distractors: ["light", "flower"] },
      { word: "rainbow", gap: [4, 6], display: "rain___", answer: "bow", distractors: ["drop", "coat"] },
      { word: "starfish", gap: [4, 7], display: "star____", answer: "fish", distractors: ["light", "ship"] },
    ],
  },
  ending_le: {
    grapheme: "-le",
    sound: "/əl/",
    hint: "words ending in LE — the E is silent",
    words: [
      { word: "table", gap: [3, 4], display: "tab__", answer: "le", distractors: ["el", "al"] },
      { word: "apple", gap: [3, 4], display: "app__", answer: "le", distractors: ["el", "al"] },
      { word: "bottle", gap: [4, 5], display: "bott__", answer: "le", distractors: ["el", "al"] },
      { word: "little", gap: [4, 5], display: "litt__", answer: "le", distractors: ["el", "al"] },
      { word: "turtle", gap: [4, 5], display: "turt__", answer: "le", distractors: ["el", "al"] },
    ],
  },
};

// Initial progress structure
export const INITIAL_PROGRESS = {
  1: { unlocked: true,  stars: {}, completed: [] },
  2: { unlocked: false, stars: {}, completed: [] },
  3: { unlocked: false, stars: {}, completed: [] },
  4: { unlocked: false, stars: {}, completed: [] },
  5: { unlocked: false, stars: {}, completed: [] },
  6: { unlocked: false, stars: {}, completed: [] },
  7: { unlocked: false, stars: {}, completed: [] },
  8: { unlocked: false, stars: {}, completed: [] },
  9: { unlocked: false, stars: {}, completed: [] },
};
