// All GPC data for Phonics Reef
// Each GPC has: id, grapheme, phoneme (IPA), sound description, words with gap position

export const LEVELS = [
  {
    id: 1,
    name: "Coral Cove",
    emoji: "🪸",
    description: "Common vowel sounds",
    color: "#FF6B6B",
    gpcs: ["ai", "ee", "oa", "igh", "oo_long", "oo_short", "ar", "or", "ur"],
  },
  {
    id: 2,
    name: "Kelp Forest",
    emoji: "🌿",
    description: "Alternative vowel sounds",
    color: "#4ECDC4",
    gpcs: ["ea_long", "ea_short", "er_stressed", "er_unstressed", "ow_loud", "ow_soft", "ie_long", "ie_short"],
  },
  {
    id: 3,
    name: "Deep Blue",
    emoji: "🌊",
    description: "Tricky patterns",
    color: "#45B7D1",
    gpcs: ["aw", "au", "air", "ear_near", "ear_bear", "are", "ue", "ew", "oe"],
  },
  {
    id: 4,
    name: "Shipwreck Bay",
    emoji: "⚓",
    description: "Consonant patterns",
    color: "#96CEB4",
    gpcs: ["tch", "dge", "kn", "wr", "ph", "wh"],
  },
  {
    id: 5,
    name: "Treasure Trove",
    emoji: "💎",
    description: "Word building",
    color: "#FFEAA7",
    gpcs: ["suffix_s", "suffix_ing", "suffix_ed", "prefix_un", "compound", "ending_le"],
  },
];

export const GPCS = {
  // LEVEL 1 — Common vowel digraphs
  ai: {
    grapheme: "ai",
    sound: "/eɪ/",
    hint: "sounds like the letter A",
    words: [
      { word: "rain", gap: [1, 2], display: "r__n", answer: "ai", distractors: ["ay", "ea"] },
      { word: "wait", gap: [1, 2], display: "w__t", answer: "ai", distractors: ["ay", "ee"] },
      { word: "train", gap: [2, 3], display: "tr__n", answer: "ai", distractors: ["ay", "oa"] },
      { word: "paid", gap: [1, 2], display: "p__d", answer: "ai", distractors: ["ay", "ea"] },
      { word: "afraid", gap: [3, 4], display: "afr__d", answer: "ai", distractors: ["ay", "ee"] },
    ],
  },
  ee: {
    grapheme: "ee",
    sound: "/iː/",
    hint: "long E sound — like a big smile!",
    words: [
      { word: "tree", gap: [1, 2], display: "tr__", answer: "ee", distractors: ["ea", "ie"] },
      { word: "green", gap: [2, 3], display: "gr__n", answer: "ee", distractors: ["ea", "ie"] },
      { word: "meet", gap: [1, 2], display: "m__t", answer: "ee", distractors: ["ea", "ie"] },
      { word: "week", gap: [1, 2], display: "w__k", answer: "ee", distractors: ["ea", "ie"] },
      { word: "sleep", gap: [2, 3], display: "sl__p", answer: "ee", distractors: ["ea", "ie"] },
    ],
  },
  oa: {
    grapheme: "oa",
    sound: "/əʊ/",
    hint: "long O sound",
    words: [
      { word: "boat", gap: [1, 2], display: "b__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "coat", gap: [1, 2], display: "c__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "road", gap: [1, 2], display: "r__d", answer: "oa", distractors: ["oe", "ow"] },
      { word: "goat", gap: [1, 2], display: "g__t", answer: "oa", distractors: ["oe", "ow"] },
      { word: "toast", gap: [1, 2], display: "t__st", answer: "oa", distractors: ["oe", "ow"] },
    ],
  },
  igh: {
    grapheme: "igh",
    sound: "/aɪ/",
    hint: "long I sound — the gh is silent!",
    words: [
      { word: "night", gap: [1, 3], display: "n___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "light", gap: [1, 3], display: "l___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "right", gap: [1, 3], display: "r___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "bright", gap: [2, 4], display: "br___t", answer: "igh", distractors: ["ie", "i-e"] },
      { word: "fight", gap: [1, 3], display: "f___t", answer: "igh", distractors: ["ie", "i-e"] },
    ],
  },
  oo_long: {
    grapheme: "oo",
    sound: "/uː/",
    hint: "long OO sound — like a ghost saying BOO!",
    words: [
      { word: "food", gap: [1, 2], display: "f__d", answer: "oo", distractors: ["ue", "ew"] },
      { word: "moon", gap: [1, 2], display: "m__n", answer: "oo", distractors: ["ue", "ew"] },
      { word: "pool", gap: [1, 2], display: "p__l", answer: "oo", distractors: ["ue", "ew"] },
      { word: "cool", gap: [1, 2], display: "c__l", answer: "oo", distractors: ["ue", "ew"] },
      { word: "spoon", gap: [2, 3], display: "sp__n", answer: "oo", distractors: ["ue", "ew"] },
    ],
  },
  oo_short: {
    grapheme: "oo",
    sound: "/ʊ/",
    hint: "short OO sound — like putting on a hood",
    words: [
      { word: "book", gap: [1, 2], display: "b__k", answer: "oo", distractors: ["ou", "u"] },
      { word: "cook", gap: [1, 2], display: "c__k", answer: "oo", distractors: ["ou", "u"] },
      { word: "foot", gap: [1, 2], display: "f__t", answer: "oo", distractors: ["ou", "u"] },
      { word: "wood", gap: [1, 2], display: "w__d", answer: "oo", distractors: ["ou", "u"] },
      { word: "good", gap: [1, 2], display: "g__d", answer: "oo", distractors: ["ou", "u"] },
    ],
  },
  ar: {
    grapheme: "ar",
    sound: "/ɑː/",
    hint: "say AAAH like at the doctor",
    words: [
      { word: "car", gap: [1, 2], display: "c__", answer: "ar", distractors: ["or", "er"] },
      { word: "star", gap: [2, 3], display: "st__", answer: "ar", distractors: ["or", "er"] },
      { word: "park", gap: [1, 2], display: "p__k", answer: "ar", distractors: ["or", "er"] },
      { word: "farm", gap: [1, 2], display: "f__m", answer: "ar", distractors: ["or", "er"] },
      { word: "shark", gap: [2, 3], display: "sh__k", answer: "ar", distractors: ["or", "er"] },
    ],
  },
  or: {
    grapheme: "or",
    sound: "/ɔː/",
    hint: "like saying OR",
    words: [
      { word: "for", gap: [1, 2], display: "f__", answer: "or", distractors: ["ar", "aw"] },
      { word: "short", gap: [2, 3], display: "sh__t", answer: "or", distractors: ["ar", "aw"] },
      { word: "corn", gap: [1, 2], display: "c__n", answer: "or", distractors: ["ar", "aw"] },
      { word: "storm", gap: [2, 3], display: "st__m", answer: "or", distractors: ["ar", "aw"] },
      { word: "sport", gap: [2, 3], display: "sp__t", answer: "or", distractors: ["ar", "aw"] },
    ],
  },
  ur: {
    grapheme: "ur",
    sound: "/ɜː/",
    hint: "like saying ER with your mouth relaxed",
    words: [
      { word: "turn", gap: [1, 2], display: "t__n", answer: "ur", distractors: ["er", "ir"] },
      { word: "hurt", gap: [1, 2], display: "h__t", answer: "ur", distractors: ["er", "ir"] },
      { word: "burst", gap: [1, 2], display: "b__st", answer: "ur", distractors: ["er", "ir"] },
      { word: "purple", gap: [1, 2], display: "p__ple", answer: "ur", distractors: ["er", "ir"] },
      { word: "nurse", gap: [1, 2], display: "n__se", answer: "ur", distractors: ["er", "ir"] },
    ],
  },

  // LEVEL 2 — Alternative vowel sounds
  ea_long: {
    grapheme: "ea",
    sound: "/iː/",
    hint: "long E sound — like EE",
    words: [
      { word: "sea", gap: [1, 2], display: "s__", answer: "ea", distractors: ["ee", "ie"] },
      { word: "dream", gap: [2, 3], display: "dr__m", answer: "ea", distractors: ["ee", "ie"] },
      { word: "meat", gap: [1, 2], display: "m__t", answer: "ea", distractors: ["ee", "ie"] },
      { word: "beach", gap: [1, 2], display: "b__ch", answer: "ea", distractors: ["ee", "ie"] },
      { word: "read", gap: [1, 2], display: "r__d", answer: "ea", distractors: ["ee", "ie"] },
    ],
  },
  ea_short: {
    grapheme: "ea",
    sound: "/ɛ/",
    hint: "short E sound — like in bed",
    words: [
      { word: "head", gap: [1, 2], display: "h__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "bread", gap: [2, 3], display: "br__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "spread", gap: [3, 4], display: "spr__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "thread", gap: [3, 4], display: "thr__d", answer: "ea", distractors: ["e", "ee"] },
      { word: "dread", gap: [2, 3], display: "dr__d", answer: "ea", distractors: ["e", "ee"] },
    ],
  },
  er_stressed: {
    grapheme: "er",
    sound: "/ɜː/",
    hint: "stressed ER — like in HER",
    words: [
      { word: "her", gap: [1, 2], display: "h__", answer: "er", distractors: ["ur", "ir"] },
      { word: "term", gap: [1, 2], display: "t__m", answer: "er", distractors: ["ur", "ir"] },
      { word: "verb", gap: [1, 2], display: "v__b", answer: "er", distractors: ["ur", "ir"] },
      { word: "stern", gap: [2, 3], display: "st__n", answer: "er", distractors: ["ur", "ir"] },
      { word: "person", gap: [1, 2], display: "p__son", answer: "er", distractors: ["ur", "ir"] },
    ],
  },
  er_unstressed: {
    grapheme: "er",
    sound: "/ə/",
    hint: "soft ER at the end — like in BUTTER",
    words: [
      { word: "better", gap: [3, 4], display: "bett__", answer: "er", distractors: ["or", "ar"] },
      { word: "under", gap: [3, 4], display: "und__", answer: "er", distractors: ["or", "ar"] },
      { word: "summer", gap: [4, 5], display: "summ__", answer: "er", distractors: ["or", "ar"] },
      { word: "winter", gap: [4, 5], display: "wint__", answer: "er", distractors: ["or", "ar"] },
      { word: "river", gap: [3, 4], display: "riv__", answer: "er", distractors: ["or", "ar"] },
    ],
  },
  ow_loud: {
    grapheme: "ow",
    sound: "/aʊ/",
    hint: "OW! like it hurts!",
    words: [
      { word: "now", gap: [1, 2], display: "n__", answer: "ow", distractors: ["ou", "oa"] },
      { word: "brown", gap: [2, 3], display: "br__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "town", gap: [1, 2], display: "t__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "crown", gap: [2, 3], display: "cr__n", answer: "ow", distractors: ["ou", "oa"] },
      { word: "growl", gap: [2, 3], display: "gr__l", answer: "ow", distractors: ["ou", "oa"] },
    ],
  },
  ow_soft: {
    grapheme: "ow",
    sound: "/əʊ/",
    hint: "soft OW — like SNOW",
    words: [
      { word: "snow", gap: [2, 3], display: "sn__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "blow", gap: [2, 3], display: "bl__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "grow", gap: [2, 3], display: "gr__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "show", gap: [2, 3], display: "sh__", answer: "ow", distractors: ["oa", "oe"] },
      { word: "flow", gap: [2, 3], display: "fl__", answer: "ow", distractors: ["oa", "oe"] },
    ],
  },
  ie_long: {
    grapheme: "ie",
    sound: "/aɪ/",
    hint: "long I sound",
    words: [
      { word: "pie", gap: [1, 2], display: "p__", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "tie", gap: [1, 2], display: "t__", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "cried", gap: [2, 3], display: "cr__d", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "tried", gap: [2, 3], display: "tr__d", answer: "ie", distractors: ["igh", "i-e"] },
      { word: "dried", gap: [2, 3], display: "dr__d", answer: "ie", distractors: ["igh", "i-e"] },
    ],
  },
  ie_short: {
    grapheme: "ie",
    sound: "/iː/",
    hint: "long E sound — like EE",
    words: [
      { word: "chief", gap: [2, 3], display: "ch__f", answer: "ie", distractors: ["ee", "ea"] },
      { word: "field", gap: [2, 3], display: "f__ld", answer: "ie", distractors: ["ee", "ea"] },
      { word: "thief", gap: [2, 3], display: "th__f", answer: "ie", distractors: ["ee", "ea"] },
      { word: "piece", gap: [1, 2], display: "p__ce", answer: "ie", distractors: ["ee", "ea"] },
      { word: "shield", gap: [2, 3], display: "sh__ld", answer: "ie", distractors: ["ee", "ea"] },
    ],
  },

  // LEVEL 3 — Tricky patterns
  aw: {
    grapheme: "aw",
    sound: "/ɔː/",
    hint: "like OR — mouth open wide!",
    words: [
      { word: "saw", gap: [1, 2], display: "s__", answer: "aw", distractors: ["au", "or"] },
      { word: "draw", gap: [2, 3], display: "dr__", answer: "aw", distractors: ["au", "or"] },
      { word: "yawn", gap: [1, 2], display: "y__n", answer: "aw", distractors: ["au", "or"] },
      { word: "crawl", gap: [2, 3], display: "cr__l", answer: "aw", distractors: ["au", "or"] },
      { word: "claw", gap: [2, 3], display: "cl__", answer: "aw", distractors: ["au", "or"] },
    ],
  },
  au: {
    grapheme: "au",
    sound: "/ɔː/",
    hint: "like OR — same sound, different spelling!",
    words: [
      { word: "author", gap: [1, 2], display: "__thor", answer: "au", distractors: ["aw", "or"] },
      { word: "August", gap: [1, 2], display: "__gust", answer: "au", distractors: ["aw", "or"] },
      { word: "dinosaur", gap: [5, 6], display: "dinos__r", answer: "au", distractors: ["aw", "or"] },
      { word: "astronaut", gap: [6, 7], display: "astron__t", answer: "au", distractors: ["aw", "or"] },
      { word: "sauce", gap: [1, 2], display: "s__ce", answer: "au", distractors: ["aw", "or"] },
    ],
  },
  air: {
    grapheme: "air",
    sound: "/ɛː/",
    hint: "like saying AIR",
    words: [
      { word: "fair", gap: [1, 3], display: "f___", answer: "air", distractors: ["are", "ear"] },
      { word: "pair", gap: [1, 3], display: "p___", answer: "air", distractors: ["are", "ear"] },
      { word: "hair", gap: [1, 3], display: "h___", answer: "air", distractors: ["are", "ear"] },
      { word: "chair", gap: [2, 4], display: "ch___", answer: "air", distractors: ["are", "ear"] },
      { word: "stair", gap: [2, 4], display: "st___", answer: "air", distractors: ["are", "ear"] },
    ],
  },
  ear_near: {
    grapheme: "ear",
    sound: "/ɪə/",
    hint: "like HEAR — rhymes with NEAR",
    words: [
      { word: "dear", gap: [1, 3], display: "d___", answer: "ear", distractors: ["eer", "air"] },
      { word: "hear", gap: [1, 3], display: "h___", answer: "ear", distractors: ["eer", "air"] },
      { word: "near", gap: [1, 3], display: "n___", answer: "ear", distractors: ["eer", "air"] },
      { word: "year", gap: [1, 3], display: "y___", answer: "ear", distractors: ["eer", "air"] },
      { word: "clear", gap: [2, 4], display: "cl___", answer: "ear", distractors: ["eer", "air"] },
    ],
  },
  ear_bear: {
    grapheme: "ear",
    sound: "/ɛː/",
    hint: "like BEAR — rhymes with CARE",
    words: [
      { word: "bear", gap: [1, 3], display: "b___", answer: "ear", distractors: ["air", "are"] },
      { word: "pear", gap: [1, 3], display: "p___", answer: "ear", distractors: ["air", "are"] },
      { word: "wear", gap: [1, 3], display: "w___", answer: "ear", distractors: ["air", "are"] },
      { word: "swear", gap: [2, 4], display: "sw___", answer: "ear", distractors: ["air", "are"] },
      { word: "tear", gap: [1, 3], display: "t___", answer: "ear", distractors: ["air", "are"] },
    ],
  },
  are: {
    grapheme: "are",
    sound: "/ɛː/",
    hint: "like CARE — same sound as air and bear!",
    words: [
      { word: "bare", gap: [1, 3], display: "b___", answer: "are", distractors: ["air", "ear"] },
      { word: "dare", gap: [1, 3], display: "d___", answer: "are", distractors: ["air", "ear"] },
      { word: "care", gap: [1, 3], display: "c___", answer: "are", distractors: ["air", "ear"] },
      { word: "share", gap: [2, 4], display: "sh___", answer: "are", distractors: ["air", "ear"] },
      { word: "spare", gap: [2, 4], display: "sp___", answer: "are", distractors: ["air", "ear"] },
    ],
  },
  ue: {
    grapheme: "ue",
    sound: "/uː/",
    hint: "long OO sound — like TRUE",
    words: [
      { word: "blue", gap: [2, 3], display: "bl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "clue", gap: [2, 3], display: "cl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "true", gap: [2, 3], display: "tr__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "glue", gap: [2, 3], display: "gl__", answer: "ue", distractors: ["ew", "oo"] },
      { word: "due", gap: [1, 2], display: "d__", answer: "ue", distractors: ["ew", "oo"] },
    ],
  },
  ew: {
    grapheme: "ew",
    sound: "/uː/",
    hint: "long OO sound — like NEW",
    words: [
      { word: "new", gap: [1, 2], display: "n__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "few", gap: [1, 2], display: "f__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "grew", gap: [2, 3], display: "gr__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "flew", gap: [2, 3], display: "fl__", answer: "ew", distractors: ["ue", "oo"] },
      { word: "threw", gap: [3, 4], display: "thr__", answer: "ew", distractors: ["ue", "oo"] },
    ],
  },
  oe: {
    grapheme: "oe",
    sound: "/əʊ/",
    hint: "long O sound — like TOE",
    words: [
      { word: "toe", gap: [1, 2], display: "t__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "goes", gap: [1, 2], display: "g__s", answer: "oe", distractors: ["ow", "oa"] },
      { word: "foe", gap: [1, 2], display: "f__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "doe", gap: [1, 2], display: "d__", answer: "oe", distractors: ["ow", "oa"] },
      { word: "hoe", gap: [1, 2], display: "h__", answer: "oe", distractors: ["ow", "oa"] },
    ],
  },

  // LEVEL 4 — Consonant patterns
  tch: {
    grapheme: "tch",
    sound: "/tʃ/",
    hint: "like CH — the T is silent!",
    words: [
      { word: "catch", gap: [2, 4], display: "ca___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "fetch", gap: [2, 4], display: "fe___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "witch", gap: [2, 4], display: "wi___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "notch", gap: [2, 4], display: "no___", answer: "tch", distractors: ["ch", "sh"] },
      { word: "hutch", gap: [2, 4], display: "hu___", answer: "tch", distractors: ["ch", "sh"] },
    ],
  },
  dge: {
    grapheme: "dge",
    sound: "/dʒ/",
    hint: "like J — badge rhymes with age!",
    words: [
      { word: "badge", gap: [2, 4], display: "ba___", answer: "dge", distractors: ["ge", "j"] },
      { word: "edge", gap: [1, 3], display: "e___", answer: "dge", distractors: ["ge", "j"] },
      { word: "bridge", gap: [3, 5], display: "bri___", answer: "dge", distractors: ["ge", "j"] },
      { word: "fudge", gap: [2, 4], display: "fu___", answer: "dge", distractors: ["ge", "j"] },
      { word: "nudge", gap: [2, 4], display: "nu___", answer: "dge", distractors: ["ge", "j"] },
    ],
  },
  kn: {
    grapheme: "kn",
    sound: "/n/",
    hint: "the K is silent — just say N!",
    words: [
      { word: "knock", gap: [0, 1], display: "__ock", answer: "kn", distractors: ["n", "gn"] },
      { word: "know", gap: [0, 1], display: "__ow", answer: "kn", distractors: ["n", "gn"] },
      { word: "knee", gap: [0, 1], display: "__ee", answer: "kn", distractors: ["n", "gn"] },
      { word: "knit", gap: [0, 1], display: "__it", answer: "kn", distractors: ["n", "gn"] },
      { word: "knife", gap: [0, 1], display: "__ife", answer: "kn", distractors: ["n", "gn"] },
    ],
  },
  wr: {
    grapheme: "wr",
    sound: "/r/",
    hint: "the W is silent — just say R!",
    words: [
      { word: "write", gap: [0, 1], display: "__ite", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrong", gap: [0, 1], display: "__ong", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrap", gap: [0, 1], display: "__ap", answer: "wr", distractors: ["r", "wh"] },
      { word: "wrist", gap: [0, 1], display: "__ist", answer: "wr", distractors: ["r", "wh"] },
      { word: "wreck", gap: [0, 1], display: "__eck", answer: "wr", distractors: ["r", "wh"] },
    ],
  },
  ph: {
    grapheme: "ph",
    sound: "/f/",
    hint: "sounds like F — phone has no F!",
    words: [
      { word: "phone", gap: [0, 1], display: "__one", answer: "ph", distractors: ["f", "wh"] },
      { word: "photo", gap: [0, 1], display: "__oto", answer: "ph", distractors: ["f", "wh"] },
      { word: "dolphin", gap: [3, 4], display: "dol__in", answer: "ph", distractors: ["f", "wh"] },
      { word: "elephant", gap: [4, 5], display: "ele__ant", answer: "ph", distractors: ["f", "wh"] },
      { word: "alphabet", gap: [4, 5], display: "alp__abet", answer: "ph", distractors: ["f", "wh"] },
    ],
  },
  wh: {
    grapheme: "wh",
    sound: "/w/",
    hint: "sounds like W — when, where, which!",
    words: [
      { word: "when", gap: [0, 1], display: "__en", answer: "wh", distractors: ["w", "ph"] },
      { word: "where", gap: [0, 1], display: "__ere", answer: "wh", distractors: ["w", "ph"] },
      { word: "which", gap: [0, 1], display: "__ich", answer: "wh", distractors: ["w", "ph"] },
      { word: "wheel", gap: [0, 1], display: "__eel", answer: "wh", distractors: ["w", "ph"] },
      { word: "while", gap: [0, 1], display: "__ile", answer: "wh", distractors: ["w", "ph"] },
    ],
  },

  // LEVEL 5 — Word building
  suffix_s: {
    grapheme: "-s / -es",
    sound: "plural",
    hint: "add S or ES to make more than one",
    words: [
      { word: "cats", gap: [3, 3], display: "cat_", answer: "s", distractors: ["es", "ing"] },
      { word: "dogs", gap: [3, 3], display: "dog_", answer: "s", distractors: ["es", "ing"] },
      { word: "catches", gap: [5, 6], display: "catch__", answer: "es", distractors: ["s", "ing"] },
      { word: "dishes", gap: [4, 5], display: "dish__", answer: "es", distractors: ["s", "ing"] },
      { word: "boxes", gap: [3, 4], display: "box__", answer: "es", distractors: ["s", "ing"] },
    ],
  },
  suffix_ing: {
    grapheme: "-ing",
    sound: "present",
    hint: "add ING to show something is happening now",
    words: [
      { word: "jumping", gap: [4, 6], display: "jump___", answer: "ing", distractors: ["ed", "er"] },
      { word: "running", gap: [4, 6], display: "runn___", answer: "ing", distractors: ["ed", "er"] },
      { word: "hunting", gap: [4, 6], display: "hunt___", answer: "ing", distractors: ["ed", "er"] },
      { word: "fishing", gap: [4, 6], display: "fish___", answer: "ing", distractors: ["ed", "er"] },
      { word: "playing", gap: [4, 6], display: "play___", answer: "ing", distractors: ["ed", "er"] },
    ],
  },
  suffix_ed: {
    grapheme: "-ed",
    sound: "past",
    hint: "add ED to show something already happened",
    words: [
      { word: "jumped", gap: [4, 5], display: "jump__", answer: "ed", distractors: ["ing", "er"] },
      { word: "hunted", gap: [4, 5], display: "hunt__", answer: "ed", distractors: ["ing", "er"] },
      { word: "painted", gap: [5, 6], display: "paint__", answer: "ed", distractors: ["ing", "er"] },
      { word: "shouted", gap: [5, 6], display: "shout__", answer: "ed", distractors: ["ing", "er"] },
      { word: "landed", gap: [4, 5], display: "land__", answer: "ed", distractors: ["ing", "er"] },
    ],
  },
  prefix_un: {
    grapheme: "un-",
    sound: "opposite",
    hint: "UN at the start means NOT or opposite",
    words: [
      { word: "unhappy", gap: [0, 1], display: "__happy", answer: "un", distractors: ["re", "dis"] },
      { word: "undo", gap: [0, 1], display: "__do", answer: "un", distractors: ["re", "dis"] },
      { word: "unlock", gap: [0, 1], display: "__lock", answer: "un", distractors: ["re", "dis"] },
      { word: "unfair", gap: [0, 1], display: "__fair", answer: "un", distractors: ["re", "dis"] },
      { word: "unload", gap: [0, 1], display: "__load", answer: "un", distractors: ["re", "dis"] },
    ],
  },
  compound: {
    grapheme: "compound",
    sound: "two words",
    hint: "two words joined together make a new word!",
    words: [
      { word: "football", gap: [4, 7], display: "foot____", answer: "ball", distractors: ["park", "play"] },
      { word: "bedroom", gap: [3, 6], display: "bed____", answer: "room", distractors: ["side", "time"] },
      { word: "sunshine", gap: [3, 7], display: "sun_____", answer: "shine", distractors: ["light", "flower"] },
      { word: "rainbow", gap: [4, 6], display: "rain___", answer: "bow", distractors: ["drop", "coat"] },
      { word: "starfish", gap: [4, 7], display: "star____", answer: "fish", distractors: ["light", "ship"] },
    ],
  },
  ending_le: {
    grapheme: "-le",
    sound: "/əl/",
    hint: "words ending in LE — the E is silent",
    words: [
      { word: "table", gap: [3, 4], display: "tab__", answer: "le", distractors: ["el", "al"] },
      { word: "apple", gap: [3, 4], display: "app__", answer: "le", distractors: ["el", "al"] },
      { word: "bottle", gap: [4, 5], display: "bott__", answer: "le", distractors: ["el", "al"] },
      { word: "little", gap: [4, 5], display: "litt__", answer: "le", distractors: ["el", "al"] },
      { word: "turtle", gap: [4, 5], display: "turt__", answer: "le", distractors: ["el", "al"] },
    ],
  },
};

// Initial progress structure
export const INITIAL_PROGRESS = {
  1: { unlocked: true, stars: {}, completed: [] },
  2: { unlocked: false, stars: {}, completed: [] },
  3: { unlocked: false, stars: {}, completed: [] },
  4: { unlocked: false, stars: {}, completed: [] },
  5: { unlocked: false, stars: {}, completed: [] },
};
